#!/bin/python3

import statistics as s
import itertools as i

_=int(input().strip())
E=list(map(int,input().strip().split(" ")))
F=list(map(int,input().strip().split(" ")))
S=set()

for j in range(len(E)):
    for k in range(F[j]):
        S.add(E[j])

def interq(x,y):
    if len(y)%2==0:
        pass
    else :
        pass 
    
    
print(S)
