#!/bin/python3

import statistics as s
import itertools as i

_=int(input().strip())
X=list(map(int,input().strip().split(" ")))
Y=list(map(int,input().strip().split(" ")))
S=set()

for j in range(len(X)):
    S.add(i.repeat(X[j],Y[j]))

def interq(x,y):
    if len(y)%2==0:
        pass
    else :
        pass 
    
    
print(S)
